### ISSUE TITLE
Trouble with the SPpermTest

### ISSUE THREAD

**Issue by Castelazo** [ahb108/rcarbon#26]
Hi, 

I'm exploring this package (which is great by the way) and I'm having an issue trying to make the Spatial Analysis with the SPpermTest that I can't solve. When I run the SPpermTest everything goes ok until it starts making the permutations, that's when R shows this error:

Error in if (max(pval) > 1) { : missing value where TRUE/FALSE needed

Everything works fine but this is the only analysis that I can't figure out what's wrong. Hope someone could help me.  
Thanks!

**Comment by ercrema** [comment]
Hi,
It's hard to tell without details, but I recall fixing a bug with a similar message a while ago for v. 1.3 (I think this was in 9df4579dbf2934765749b46b3d6ff8138f0d28aa). The problem was caused when sites were sparse and/or the distance bandwidth too short.  

Are you using the CRAN version (v.1.2?) if that's the case would you mind running this on the development version where this is fixed? You will need to install `devtools` and then run `devtools::install_github('ahb108/rcarbon')`. The function has been renamed `sptest()` but your code should be running without any issues. If you still have issues I will need to debug using your data if you don't mind.

**Comment by Castelazo** [comment]
Hi, 
I tried what you said but I still have the same problem with the function sptest:  
Error in if (x[i + 1] == 0 | x[i] == 0) { : 
  missing value where TRUE/FALSE needed

It looks that I still have the same error so I can send you the data to your mail (is enrico.crema@gmail.com still active?).

Thanks a lot!

**Comment by ercrema** [comment]
Yes the email address is correct. Could you also send the full script generating the error (including the random seed)?

**Comment by ercrema** [comment]
Fixed in commit e2c4d305997ee7b0ef997d383b7ea82a37a8c393
The issue was caused by some bins with dates having their entire probability mass outside the `timeRange` of analysis. This then produced `NaN`s which in turn caused the error in the computation of the rate of change.
